dubbo:
  application:
    name: front
  registry:
    address: zookeeper://123.57.52.37:2181
  scan:
    base-packages: com.lanqiao.music.server.service
  protocol:
    host: 192.168.0.148
    id: dubbo
    name: dubbo
